# Generated by Django 3.1.6 on 2021-02-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('sort', models.IntegerField(default=1, verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('auth_type', models.CharField(max_length=128, verbose_name='权限组名称')),
                ('auth_desc', models.CharField(max_length=255, verbose_name='权限组描述')),
                ('routers', models.TextField(verbose_name='前端路由')),
            ],
            options={
                'verbose_name': '权限组表',
                'verbose_name_plural': '权限组表',
                'db_table': 'users_auth_table',
            },
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('sort', models.IntegerField(default=1, verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('group_type', models.CharField(choices=[('SuperAdmin', '超级管理员'), ('Admin', '管理员'), ('NormalUser', '普通用户')], max_length=128, verbose_name='用户组类型')),
                ('group_type_cn', models.CharField(max_length=128, verbose_name='用户组类型_cn')),
                ('group_desc', models.CharField(max_length=255, verbose_name='用户组描述')),
            ],
            options={
                'verbose_name': '用户组表',
                'verbose_name_plural': '用户组表',
                'db_table': 'users_group_table',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('sort', models.IntegerField(default=1, verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('username', models.CharField(blank=True, default='', max_length=32, verbose_name='用户账号')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='用户密码')),
                ('mobile', models.CharField(blank=True, default='', max_length=11, verbose_name='用户手机号')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='用户邮箱')),
                ('real_name', models.CharField(blank=True, default='', max_length=16, verbose_name='真实姓名')),
                ('id_num', models.CharField(blank=True, default='', max_length=18, verbose_name='身份证号')),
                ('nick_name', models.CharField(blank=True, default='', max_length=32, verbose_name='昵称')),
                ('region', models.CharField(blank=True, default='', max_length=255, verbose_name='地区')),
                ('avatar_url', models.CharField(blank=True, default='', max_length=255, verbose_name='头像')),
                ('open_id', models.CharField(blank=True, default='', max_length=255, verbose_name='微信openid')),
                ('union_id', models.CharField(blank=True, default='', max_length=255, verbose_name='微信unionid')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('is_freeze', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否冻结/是否封号')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='上次登录时间')),
                ('auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.authmodel', verbose_name='权限组')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.groupmodel', verbose_name='用户组')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'users_info_table',
            },
        ),
        migrations.CreateModel(
            name='AuthPermissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('sort', models.IntegerField(default=1, verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('object_name', models.CharField(max_length=128, verbose_name='功能名称')),
                ('object_name_cn', models.CharField(max_length=128, verbose_name='功能名称_cn')),
                ('auth_list', models.BooleanField(default=False, verbose_name='查看')),
                ('auth_create', models.BooleanField(default=False, verbose_name='新增')),
                ('auth_update', models.BooleanField(default=False, verbose_name='修改')),
                ('auth_destroy', models.BooleanField(default=False, verbose_name='删除')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_permissions', to='users.authmodel', verbose_name='权限组')),
            ],
            options={
                'verbose_name': '权限菜单表',
                'verbose_name_plural': '权限菜单表',
                'db_table': 'users_permission_table',
            },
        ),
    ]
