# Generated by Django 3.1.6 on 2021-02-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_delete_ordermodel'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddressModel',
        ),
    ]
