# Generated by Django 3.1.6 on 2021-02-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_delete_ordermodel'),
        ('users', '0003_shippingaddressmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddressModel',
        ),
    ]
