# Generated by Django 3.1.6 on 2021-02-18 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_shippingaddressmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('sort', models.IntegerField(default=1, verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('region', models.CharField(blank=True, default='', max_length=255, verbose_name='地区')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='详细地址')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_address', to='users.usermodel', verbose_name='收货人')),
            ],
            options={
                'verbose_name': '收货地址表',
                'verbose_name_plural': '收货地址表',
                'db_table': 'users_address_table',
            },
        ),
    ]
