# Generated by Django 3.1.6 on 2021-02-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_shippingaddressmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddressmodel',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='用户手机号'),
        ),
        migrations.AddField(
            model_name='shippingaddressmodel',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='真实姓名'),
        ),
    ]
