# Generated by Django 3.1.6 on 2021-02-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210218_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddressmodel',
            old_name='real_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shippingaddressmodel',
            old_name='mobile',
            new_name='tel',
        ),
    ]
