# Generated by Django 3.1.6 on 2021-02-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210228_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddressmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddressmodel',
            name='region',
        ),
        migrations.AddField(
            model_name='shippingaddressmodel',
            name='areaCode',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='地区码'),
        ),
        migrations.AddField(
            model_name='shippingaddressmodel',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='市'),
        ),
        migrations.AddField(
            model_name='shippingaddressmodel',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='shippingaddressmodel',
            name='county',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='区'),
        ),
        migrations.AddField(
            model_name='shippingaddressmodel',
            name='isDefault',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='默认'),
        ),
        migrations.AddField(
            model_name='shippingaddressmodel',
            name='postalCode',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='邮编'),
        ),
        migrations.AddField(
            model_name='shippingaddressmodel',
            name='province',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='省/直辖市'),
        ),
    ]
