# Generated by Django 3.1.7 on 2021-03-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_shippingaddressmodel_addressdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddressmodel',
            name='current',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='被使用'),
        ),
    ]
