# Generated by Django 3.1.6 on 2021-02-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='推荐价格'),
        ),
        migrations.AlterField(
            model_name='sellingproductmodel',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='售价'),
        ),
    ]
