# Generated by Django 3.1.6 on 2021-02-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20210218_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
