# Generated by Django 3.1.6 on 2021-02-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_ordermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
