# Generated by Django 3.1.6 on 2021-02-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_auto_20210218_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_book', to='mall.CategoryModel', verbose_name='类别'),
        ),
    ]
