# Generated by Django 3.1.6 on 2021-02-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210218_2312'),
        ('mall', '0008_auto_20210220_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='count',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=30, verbose_name='总价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='image',
            field=models.URLField(verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ManyToManyField(related_name='category_product', to='mall.CategoryModel', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='cover',
            field=models.URLField(blank=True, null=True, verbose_name='封面'),
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('sort', models.IntegerField(default=1, verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer_cart', to='users.usermodel', verbose_name='买家')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller_cart', to='users.usermodel', verbose_name='卖家')),
                ('selling_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='selling_product_cart', to='mall.sellingproductmodel', verbose_name='对应商品')),
            ],
            options={
                'verbose_name': '购物车信息表',
                'verbose_name_plural': '购物车信息表',
                'db_table': 'cart_table',
            },
        ),
    ]
