# Generated by Django 3.1.6 on 2021-02-28 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_shippingaddressmodel_addressdetail'),
        ('mall', '0009_auto_20210221_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('sort', models.IntegerField(default=1, verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('fraction', models.IntegerField(verbose_name='数量')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_rate', to='mall.productmodel', verbose_name='对应商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_rate', to='users.usermodel', verbose_name='评分人')),
            ],
            options={
                'verbose_name': '商品评分表',
                'verbose_name_plural': '商品评分表',
                'db_table': 'rate_table',
            },
        ),
    ]
